name: Metrics

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ndhoang1401-ops
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Ho_Chi_Minh
          config_padding: 10%
          filename: github-metrics.svg
          output_action: commit
          committer_branch: main

          # 📅 Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # 💻 Languages - TẮT HẾT TÍNH NĂNG NẶNG
          plugin_languages: yes
          plugin_languages_analysis_timeout: 10
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_indepth: no
          plugin_languages_details: percentage

          # 🏆 Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 6

          # 📝 Activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
